In [42]:
import pandas as pd

df = pd.read_csv('informacoes.csv')

display(df)

,id,nome,sobrenome,email,genero,ip_address,ultimo_login,cidade,data_nascimento
0,1,Salomone,Cattel,NaN,Male,4.86.58.32,11/2/2025,NaN,NaN
1,2,Orelee,Petasch,opetasch1@weebly.com,Female,247.218.6.7,1/3/2026,Las Terrenas,4/21/2025
2,3,Cherida,Restieaux,crestieaux2@techcrunch.com,Female,32.190.83.61,2/19/2025,NaN,NaN
3,4,Welby,Woodhead,NaN,Male,NaN,4/25/2025,Mariscala,NaN
4,5,Denise,Zebedee,dzebedee4@uol.com.br,Female,35.255.10.197,1/7/2026,Shorko,12/18/2025
...,...,...,...,...,...,...,...,...,...
995,996,Helge,Swithenby,hswithenbyrn@unc.edu,NaN,9.113.240.16,NaN,Ljungskile,10/2/2025
996,997,Eadmund,Hanratty,ehanrattyro@w3.org,Male,NaN,NaN,Lekas,6/12/2025
997,998,Sharyl,Terran,sterranrp@ebay.co.uk,Genderfluid,49.15.40.97,11/10/2025,Pampachiri,7/7/2025
998,999,Esther,Eagger,eeaggerrq@exblog.jp,NaN,117.106.52.239,8/18/2025,NaN,6/4/2025
999,1000,Karrah,Wyre,kwyrerr@tumblr.com,NaN,186.112.150.31,NaN,NaN,3/14/2025

In [43]:
# tranformar os tipos de dados para o formato correto
# ultimo_login, data_nascimento

df['ultimo_login'] = pd.to_datetime(df['ultimo_login'])
df['data_nascimento'] = pd.to_datetime(df['data_nascimento'])
df = df.drop_duplicates()

display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1000 non-null   int64
 1   nome             1000 non-null   str
 2   sobrenome        1000 non-null   str
 3   email            874 non-null    str
 4   genero           725 non-null    str
 5   ip_address       643 non-null    str
 6   ultimo_login     665 non-null    datetime64[us]
 7   cidade           630 non-null    str
 8   data_nascimento  933 non-null    datetime64[us]
dtypes: datetime64[us](2), int64(1), str(6)
memory usage: 70.4 KB

None

In [44]:
# agrupar ultimo_login com cidade
df_grouped = df.groupby('cidade')['ultimo_login'].count().reset_index()
# remover nan
df_grouped = df_grouped.dropna()

df_grouped.sort_values(by='ultimo_login', ascending=False, inplace=True)

display(df_grouped)

          cidade  ultimo_login
358  Montpellier             2
600     Yasothon             1
15     Aquitania             1
16     Ar Rawḑah             1
18       Aranhas             1
..           ...           ...
597     Yanjiang             0
599      Yanzhou             0
602    Yelkhovka             0
8          Alice             0
622        Şanā’             0

[623 rows x 2 columns]

In [45]:


import plotly.express as px

#mostrar grafico de barras com a quantidade de logins por cidade
fig = px.bar(df_grouped.head(5), x='cidade', y='ultimo_login', title='Quantidade de logins por cidade',)
fig.show()

In [46]:
# agrupar ultimo_login com genero
df_grouped = df.groupby('genero')['ultimo_login'].count().reset_index()
# remover nan
df_grouped = df_grouped.dropna()
df_grouped.sort_values(by='ultimo_login', ascending=False, inplace=True)
display(df_grouped)

        genero  ultimo_login
2       Female           219
5         Male           218
1     Bigender            10
3  Genderfluid             9
7   Polygender             8
4  Genderqueer             8
0      Agender             7
6   Non-binary             6

In [47]:
# grafico de barras com a quantidade de logins por genero
fig = px.bar(df_grouped, x='genero', y='ultimo_login', title='Quantidade de logins por genero',)
fig.show()

In [48]:
# remover nan de data_nascimento
df = df.dropna(subset=['data_nascimento'])

# grafico de barras com a quantidade de aniversarios por mes
df['mes'] = df['data_nascimento'].dt.month_name()

# ordenar os meses
meses_ordenados = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
df['mes'] = pd.Categorical(df['mes'], categories=meses_ordenados, ordered=True)

df_grouped = df.groupby('mes').size().reset_index(name='aniversarios')
fig = px.bar(df_grouped, x='mes', y='aniversarios', title='Quantidade de aniversários por mês')
fig.show()